# Generated by Django 3.2.15 on 2022-09-14 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='clientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_cliente', models.CharField(max_length=80)),
                ('razon_social', models.CharField(max_length=100, unique=True)),
                ('nombre_contacto', models.CharField(max_length=100)),
                ('puesto', models.CharField(max_length=20)),
                ('telefono_contacto', models.CharField(max_length=20)),
                ('email_contacto', models.CharField(max_length=50)),
                ('email_empresa', models.CharField(max_length=50)),
                ('telefono_empresa', models.CharField(max_length=20)),
                ('direccion_empresa', models.CharField(max_length=100)),
                ('cfdi', models.CharField(max_length=20)),
                ('fecha_creacion', models.DateField(max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='paquete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_paquete', models.CharField(max_length=80, unique=True)),
                ('duracion', models.CharField(max_length=80, unique=True)),
                ('frecuencia', models.CharField(max_length=80, unique=True)),
                ('precio', models.IntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='campaña',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_campaña', models.CharField(max_length=80, unique=True)),
                ('status', models.CharField(blank=True, choices=[('A', 'Activo'), ('I', 'Inactivo'), ('S', 'Suspendido')], default='A', max_length=30)),
                ('video', models.CharField(max_length=80, null=True, unique=True)),
                ('imagen', models.CharField(max_length=80, null=True, unique=True)),
                ('fecha_inicial', models.DateField(max_length=80, unique=True)),
                ('fecha_final', models.DateField(max_length=80, unique=True)),
                ('fecha_creacion', models.DateField(max_length=80, unique=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.clientes')),
                ('paquete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.paquete')),
            ],
        ),
    ]
