# Generated by Django 3.2.15 on 2022-09-26 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaña',
            name='status',
            field=models.CharField(max_length=11),
        ),
    ]
