# Generated by Django 3.2.15 on 2022-09-20 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaña',
            name='imagen',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='campaña',
            name='video',
            field=models.FileField(upload_to=''),
        ),
    ]
