# Generated by Django 3.2.15 on 2022-09-20 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0002_auto_20220920_1124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaña',
            name='imagen',
            field=models.FileField(upload_to=''),
        ),
    ]
