# Generated by Django 3.2.15 on 2022-09-26 16:03

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0003_auto_20220926_1034'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaña',
            name='cliente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='principal.clientes'),
        ),
        migrations.AddField(
            model_name='campaña',
            name='fecha_creacion',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='campaña',
            name='fecha_final',
            field=models.DateField(default=django.utils.timezone.now, max_length=80),
        ),
        migrations.AddField(
            model_name='campaña',
            name='fecha_inicial',
            field=models.DateField(default=django.utils.timezone.now, max_length=80),
        ),
        migrations.AddField(
            model_name='campaña',
            name='imagen',
            field=models.FileField(default=-1.0, upload_to='album/images'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='campaña',
            name='paquete',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='principal.paquete'),
        ),
        migrations.AddField(
            model_name='campaña',
            name='status',
            field=models.CharField(choices=[('ACTIVO', 'ACTIVO'), ('INACTIVO', 'INACTIVO'), ('SUSPENDIDO', 'SUSPENDIDO')], default=-1.0, max_length=11),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='campaña',
            name='video',
            field=models.FileField(default=-1.0, upload_to='album/videos'),
            preserve_default=False,
        ),
    ]
