# Generated by Django 3.2.15 on 2022-09-20 17:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0003_alter_campaña_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaña',
            name='fecha_creacion',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
