# Generated by Django 3.2.15 on 2022-09-26 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0004_auto_20220926_1103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaña',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
