# Generated by Django 3.2.15 on 2022-09-27 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0005_alter_campaña_fecha_creacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaña',
            name='cliente',
            field=models.OneToOneField(default=-1.0, on_delete=django.db.models.deletion.CASCADE, to='principal.clientes'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='campaña',
            name='paquete',
            field=models.OneToOneField(default=-1.0, on_delete=django.db.models.deletion.CASCADE, to='principal.paquete'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='campaña',
            name='status',
            field=models.CharField(choices=[('ACTIVO', 'ACTIVO'), ('INACTIVO', 'INACTIVc'), ('SUSPENDIDO', 'SUSPENDIDO')], max_length=11),
        ),
    ]
