# Generated by Django 3.2.15 on 2022-09-27 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0006_auto_20220927_0915'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaña',
            name='cliente',
        ),
        migrations.AddField(
            model_name='campaña',
            name='cliente',
            field=models.ManyToManyField(to='principal.clientes'),
        ),
        migrations.RemoveField(
            model_name='campaña',
            name='paquete',
        ),
        migrations.AddField(
            model_name='campaña',
            name='paquete',
            field=models.ManyToManyField(to='principal.paquete'),
        ),
    ]
