# Generated by Django 3.2.15 on 2022-09-27 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0007_auto_20220927_0917'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaña',
            name='cliente',
        ),
        migrations.AddField(
            model_name='campaña',
            name='cliente',
            field=models.OneToOneField(default=-1.0, on_delete=django.db.models.deletion.CASCADE, to='principal.clientes'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='campaña',
            name='paquete',
        ),
        migrations.AddField(
            model_name='campaña',
            name='paquete',
            field=models.OneToOneField(default=-1.0, on_delete=django.db.models.deletion.CASCADE, to='principal.paquete'),
            preserve_default=False,
        ),
    ]
