# Generated by Django 3.2.15 on 2022-09-27 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0008_auto_20220927_0920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaña',
            name='cliente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='principal.clientes'),
        ),
        migrations.AlterField(
            model_name='campaña',
            name='paquete',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='principal.paquete'),
        ),
        migrations.AlterField(
            model_name='campaña',
            name='status',
            field=models.CharField(choices=[('ACTIVO', 'ACTIVO'), ('INACTIVO', 'INACTIVO'), ('SUSPENDIDO', 'SUSPENDIDO')], max_length=11),
        ),
    ]
