# Generated by Django 3.2.15 on 2022-10-13 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0009_auto_20220927_1001'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaña',
            name='categoria',
            field=models.CharField(choices=[('AGROPECUARIO', 'AGROPECUARIO'), ('AGRUPACIONES', 'AGRUPACIONES'), ('ALIMENTOS', 'ALIMENTOS'), ('AUTOMOTRIZ Y AFINES', 'AUTOMOTRIZ Y AFINEZ'), ('BEBIDAS', 'BEBIDAS'), ('COMPUTO, INTERNET, TELEFONIA Y TV PAGA', 'COMPUTO,INTERNET,TELEFONIAYTVPAGA')], default=-1.0, max_length=50),
            preserve_default=False,
        ),
    ]
